### ISSUE TITLE
NodeJS + Error: 'data should NOT have additional properties'

### ISSUE THREAD

**Issue by syedahmedss** [smsglobal/smsglobal-node#11]
I try to integrate SMSGlobal Gateway in my NodeJS application. I use the example code I am getting error.
see below my code .

const SMSGLOBAL_API_KEY = '1233123123213123';
const SMSGLOBAL_API_SECRET = '123123123123123';
const smsglobal = require('smsglobal')(SMSGLOBAL_API_KEY, SMSGLOBAL_API_SECRET);
const util = require('util');

// Send sms
var payload = {
  origin: 'SMSGlobal',
  destiantion: '97150888888',
  message: 'Test sms from node sdk',
};

smsglobal.sms.send(payload, function(error, response) {

  if (response) {
    console.log('Response:', response.data ? response.data : response);
  }

  if (error) {
    console.log('Error:', util.inspect(error, {showHidden: false, depth: null, colors: true}));
  }

});

**Comment by spcheema** [comment]
Thanks for reporting this issue @syedahmedss. Actually there was a typo `destiantion` in the provided example. The correct spelling is `destination`. This typo has been fixed now.
